---
name: CI - Main
run-name: Continuous Integration on ${{ github.head_ref || github.ref_name }} by ${{ github.actor }}

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:

  pre-commit:
    name: Call Prek
    uses: irishlab-io/.github/.github/workflows/reusable-prek.yml@main
    with:
      skips: "actionlint,ggshield,pin-github-action"

  secret:
    needs:
      - pre-commit
    name: Call Git Guardian
    uses: irishlab-io/.github/.github/workflows/reusable-gitguardian.yml@main
    secrets:
      GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}

  hugo-deploy:
    needs:
      - pre-commit
      - secret
    name: Call Deploy to GitHub Pages
    uses: irishlab-io/.github/.github/workflows/reusable-hugo-ghpages.yml@main
    with:
      hugo-dir: "./docs"
      publish-dir: "./docs/public"
    permissions:
      contents: read
      pages: write
      id-token: write
