---
name: CI - Main

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:

  pre-commit:
    name: Call Prek
    uses: irishlab-io/.github/.github/workflows/reusable-prek.yml@main
    with:
      skips: "actionlint,ggshield,pin-github-action"

  secret:
    needs:
      - pre-commit
    name: Call Git Guardian
    uses: irishlab-io/.github/.github/workflows/reusable-gitguardian.yml@main
    secrets:
      GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}

  hugo-deploy:
    needs:
      - pre-commit
      - secret
    name: Deploy to GitHub Pages
    uses: irishlab-io/.github/.github/workflows/reusable-hugo-ghpages.yml@main
    with:
      hugo-version: "latest"
      hugo-extended: true
      publish-dir: "./docs/public"
      hugo-args: "--minify"
      submodules: "true"
    permissions:
      contents: read
      pages: write
      id-token: write
